### ISSUE TITLE
[SASS] Application broken since v.3.3

### ISSUE THREAD

**Issue by brunolemos** [fourseven/meteor-scss#120]
I'm using SASS (not SCSS) and having this error on all files that has an import:

```
   While processing files with fourseven:scss (for target web.browser):
   /main.sass: Scss compiler error: invalid top-level expression
```

Or this:

```
   /client/templates/components/header/header.sass: Scss compiler error: top-level @import directive must be
   terminated by ';'
```

It seems that it's trying to compile my .sass as an .scss.

REPRODUCTION:

**main.sass**

```
@import "teste"
```

**_teste.sass** _THIS IS NOT WORKING ANYMORE_

```
body
  background: red
```

**_teste.sass** _this works, but shouldn't because it's a .sass_

```
body {
  background: red;
}
```

**Comment by brunolemos** [comment]
Current workaround: downgrade to v3.2.0, which works fine:

````
meteor add fourseven:scss@=3.2.0
````

**Comment by sebakerckhof** [comment]
Fixed in master, will be published soon

**Comment by brunolemos** [comment]
As it was not fixed, I created a pull request adding a unit test that shows my problem.

**Comment by sebakerckhof** [comment]
Ok, this seems like problem with node-sass, since indentedSyntax is set to true for the sass file, but still it treats the imported file as scss-style.

**Comment by sebakerckhof** [comment]
https://github.com/sass/node-sass/issues/1192

**Comment by sebakerckhof** [comment]
I'll reopen till this is fixed in node-sass

**Comment by fourseven** [comment]
Hi @brunolemos - thanks for the test, this issue still exists in node-sass – so follow that and we'll have this meteor package fixed once it's fixed upstream (the master branch here with your tests has the sass test disabled because of it).

**Comment by matfin** [comment]
Just added this to a new sample meteor app I am working on and the issue is still there. I am using version 3.4.1 and still getting the same issue as reported in
https://github.com/fourseven/meteor-scss/issues/150

If you want to see what is happening you can clone the repository https://github.com/matfin/gfmtest

I am using Meteor 1.2.1

**Comment by sebakerckhof** [comment]
Yes, it's still not fixed in libsass

**Comment by kdanninger** [comment]
+1

**Comment by sebakerckhof** [comment]
From https://github.com/sass/node-sass/issues/1192:
> So for importing *.sass files we have to wait a patch.
> You guys can covert all sass to scss in one command
`sass-convert -R -F sass -T scss .`

Since the indented syntax doesn't seem to be a priority for libsass, this might be a solution for some of you.

**Comment by brunolemos** [comment]
I use jade and coffeescript in my projects, so it's consistent to use sass (all indented syntax).
I'll keep using v3.2.0 and wait for a fix (or search for an alternative solution).

**Comment by kdanninger** [comment]
Booo :crying_cat_face: would like to see this fixed eventually

**Comment by rista404** [comment]
If this helps, I get a similar error message:

```
=> Errors prevented startup:

   While processing files with fourseven:scss (for target web.browser):
   /client/stylesheets/style.sass: Scss compiler error: @import directive requires a url or quoted path


=> Your application has errors. Waiting for file change.
```

This was happening from `3.3.3` as I recall, and I am using `3.2.0` since then.
I hope this will be fixed eventually.

Cheers!

**Comment by andersr** [comment]
It appears that compiling of .sass files still is not working (due to the upstream issue)  However, it is not clear from the ReadMe that this is the case and I just spent the last couple hours trying to troubleshoot this until I discovered this issue.  Had I known, I would have just gone with .scss right away.

It would be great if a note could be added to the ReadMe that explains that there may be issues with compiling of .sass files.

**Comment by calvinfu1128** [comment]
compiling sass fails, downgraded to v3.2 as work around at the moment

**Comment by KaizenCris** [comment]
Same issue
In the end I downgraded from 3.8.0_1 to 3.2.0. Are there any plans to fix the .sass import?

**Comment by exequiel09** [comment]
Same Issue.

**Comment by theosp** [comment]
Check my comment here: https://github.com/fourseven/meteor-scss/issues/220#issuecomment-251994687

**Comment by Fauphi** [comment]
Looks like you cannot install v3.2.0 of fourseven:scss anymore. 

`Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-46_binding.node": HTTP error 404 Not Found`

Any workarounds for that?
I'm on OSX 10.12.2

**Comment by sebakerckhof** [comment]
I'll close this issue since it doesn't seem likely node-sass will fix the support for the older sass syntax, since it's considered deprecated. So there's not much we can do about it.

**Comment by smeijer** [comment]
Had this error after adding Bulma,

```bash
meteor add fourseven:scss
meteor npm install bulma
```

client/main.scss
```scss
@charset "utf-8";
@import "../node_modules/bulma/bulma.sass";
```

Is there any known way to get this package working with [`Bulma`](https://bulma.io)?
