### ISSUE TITLE
Support options from pre 3.3

### ISSUE THREAD

**Issue by sebakerckhof** [fourseven/meteor-scss#124]
-indexFile
-includePaths (should be unnecessary now there is cross-package imports)

**Comment by sebakerckhof** [comment]
indexFile will be very hard/ugly to support in the current build system.

includePaths should be possible, but this is mainly being used for cross-package imports, and there is a better way now.

**Comment by TimFletcher** [comment]
I'm currently using a pattern whereby I have a `Component.scss` file for each of my react components. Each component has a root element (div, usually) with the component class and the scss file is scoped to that component like so:

**components/SomeComponent.jsx**
```
<div className="SomeComponent>
  ... markup ...
</div>
```

**components/SomeComponent.scss**
```
.SomeComponent {
  ... styles ...
}
```

I'm using `indexFile`/ `indexFilePath` from `3.2.0` like this in my `scss.json` so that each component's scss file is appended automatically to the bottom of `client/stylesheets/main.scss`.

```
{
  "useIndex" : true,
  "indexFilePath" : "client/stylesheets/main.scss"
}
```
At the top of `client/stylesheets/main.scss` I can import all my global variables and mixins etc. and they're all recognized in each component's scss file. It works really well.

If `indexFile` doesn't make it into the Meteor 1.2 version of this package do you know any other/better way of structuring my scss files? Unfortunately with 3.3 all my components' scss files are getting autodiscovered and imported before the indexFile which is causing all the imports to break. I *could* add a line at the top of every components' file but I'd like to try and avoid the boilerplate.

**Comment by sebakerckhof** [comment]
You can do exactly as you're doing, but prefix every component scss file with an underscore, that way the build system knows it shouldn't process the file directly. (alternatively, if you work inside a package, you could use the isImport flag using the addFiles method).

However, you will have to build the main.scss yourself, meaning the new version of meteor-scss will not generate the file for you anymore (at this moment).

**Comment by TimFletcher** [comment]
Thanks, it worked. Additionally I had to go through all the Bourbon imports and update them from a relative to full path. e.g. in **client/sass/base/_base.scss**. For example I had to change

`@import "variables";`

to 

`@import "{}/client/sass/base/variables";`

So that the import in my main sass file **client/stylesheets/main.scss** 

`@import '{}/client/sass/base/base';`

Would work too.

**Comment by sebakerckhof** [comment]
Yeah, but relative urls should work agaib in the next release.

**Comment by TimFletcher** [comment]
Awesome. Thanks!

**Comment by SachaG** [comment]
Same issue here. Hope to get relative URLs working again soon!

**Comment by sebakerckhof** [comment]
Hey @SachaG , normally it should be fixed on the master branch, but we're waiting to publish till node-sass 3.4 goes out of beta (the issue was related to node-sass), but you can try it by cloning the master branch.

**Comment by SachaG** [comment]
OK, good to know!

**Comment by juliancwirko** [comment]
As mentioned in https://github.com/fourseven/meteor-scss/issues/118 could we have a 'fourseven:scss 3.4.0-beta1' version?

**Comment by fourseven** [comment]
`3.4.0-beta1` was just published which should fix this. :balloon:

**Comment by kristijanhusak** [comment]
I'm still having issue that I explained here https://github.com/fourseven/meteor-scss/issues/122 .
I'm not able to import anything from `.meteor` folder, or i'm doing it wrong:
```
@import '{}/.meteor/local/bower/inuit-spacing/trumps.spacing';
@import '{}/.meteor/local/bower/inuit-spacing-responsive/trumps.spacing-responsive';
```

Errors:
```
=> Errors prevented startup:                  
   
   While processing files with fourseven:scss (for target web.browser):
   /scss/screen.scss: Scss compiler error: File to import: {}/.meteor/local/bower/inuit-defaults/settings.defaults
   not found in file: /home/kristijan/code/reportnest/{}/scss/screen.scss
```

**Comment by sebakerckhof** [comment]
Importing from the .meteor folder is not supported, since these files are not tracked by the Meteor build system. This was a hack from before cross-package imports.
The other packages should be modified to comply with meteor 1.2. Until then you'll have to use fourseven:scss 3.2.0

**Comment by derwaldgeist** [comment]
@sebakerckhof: If importing from the .meteor folder is not supported any more, how should I import SASS files that have been downloaded by ```mquandalle:bower```? I'm using this a lot, since not all SASS frameworks are available as Atmosphere packages. And the bower components are automatically installed under the .meteor folder.

**Comment by juliancwirko** [comment]
It has no any relation with this package which is really good. It seems that bower package uses old Meteor hack to achieve its goals.
