### ISSUE TITLE
No compatible binary (OSX, METEOR@1.3.4.1)

### ISSUE THREAD

**Issue by timbrandin** [fourseven/meteor-scss#187]
Seems like `meteor publish-for-arch` is necessary to solve this?

```
$ meteor update fourseven:scss
=> Errors while upgrading packages:

While checking for fourseven:scss@3.8.0:
error: No compatible binary build found for this package. Contact the package author and
ask them to publish it for your platform.
```

**Comment by sebakerckhof** [comment]
Yeah, but I can't seem to access the OSX build servers at this moment and I can also not unpublish the latest version.
Please stick to version 3.4.3 until this is resolved.

**Comment by sebakerckhof** [comment]
Tracked here: https://github.com/meteor/meteor/issues/7314

**Comment by sebakerckhof** [comment]
Done

**Comment by pfafman** [comment]
I am still getting this error.  Tried removing and reinstalling the package.

```
$ meteor add fourseven:scss
 => Errors while adding packages:

While checking for fourseven:scss@3.8.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

**Comment by sebakerckhof** [comment]
Seems like something went wrong with previous build. Can you try again now? (patch version 3.8.0_1)

**Comment by pfafman** [comment]
Working with 3.8.0_1.  Thanks

**Comment by c9s** [comment]
3.8.0_1 failed on travis ci (Ubuntu linux)
