### ISSUE TITLE
libc++ library load issue

### ISSUE THREAD

**Issue by mattlinares** [fourseven/meteor-scss#58]
I'm getting the following error (this is an excerpt, [full error here](http://pastebin.com/y452BeDj): 

```
While loading plugin `fourseven:scss` from package `fourseven:scss`:
module.js:356:32:
dlopen(/Users/methuselah/.meteor/packages/fourseven_scss/.1.0.0.wp4tvk++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/plugin.fourseven:scss.os.osx.x86_64/npm/fourseven:scss/node_modules/node-sass/bin/darwin-x64-v8-3.14/binding.node,
1): Library not loaded: /usr/lib/libc++.1.dylib
Referenced from:
/Users/methuselah/.meteor/packages/fourseven_scss/.1.0.0.wp4tvk++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/plugin.fourseven:scss.os.osx.x86_64/npm/fourseven:scss/node_modules/node-sass/bin/darwin-x64-v8-3.14/binding.node
```

It's proving tricky to install libc++ and its dependencies. Is there anything else you can suggest to get fourseven:scss running?

Thanks

**Comment by fourseven** [comment]
I'm guessing you're running OS X? Which version?

**Comment by mattlinares** [comment]
Yes 10.6.8

**Comment by fourseven** [comment]
Hah you're the second person in a week still running 10.6.8 (#56) - I've just released 2.0.0-beta_1 to rebuild the package though the meteor build system. Can you give that a try and get back to me please?

**Comment by mattlinares** [comment]
Do you mean 1.0.0-beta_1? You're only at 1.0.0 right?

I'm not perfectly sure how to do this other than running the server which auto updates packages (still not working). Or is this done some other way, e.g. by changing the line in `.meteor/versions` that says:

"fourseven:scss@1.0.0"

to:

"fourseven:scss@1.0.0-beta_1"

**Comment by fourseven** [comment]
```sh
{15:59}~/Development/fourseven:scss:master ✗ ➭ meteor show fourseven:scss
Package fourseven:scss:

Version 0.9.4         Style with attitude.
Version 0.9.5         Style with attitude.
Version 0.9.6         Style with attitude and autoprefixer.
Version 1.0.0         Style with attitude and autoprefixer.
Version 2.0.0-beta    Style with attitude and autoprefixer.
Version 2.0.0-beta_1  Style with attitude and autoprefixer.

Maintained by: fourseven.
Git repository at: https://github.com/fourseven/meteor-scss.git
```

you want to `meteor add fourseven:scss@2.0.0-beta_1` and see what happens.

**Comment by mattlinares** [comment]
Tried that:

```
meteor add fourseven:scss@2.0.0-beta_1
 => Errors while adding packages:

While loading plugin `fourseven:scss` from package `fourseven:scss`:
module.js:356:32:
dlopen(/Users/methuselah/.meteor/packages/fourseven_scss/.2.0.0-beta_1.zuywo8++os.osx.x86_64+web.browser+web.cordova/plugin.fourseven:scss.os.osx.x86_64/npm/fourseven:scss/node_modules/node-sass/vendor/darwin-x64/binding.node,
1): Library not loaded: /usr/lib/libc++.1.dylib
Referenced from:
/Users/methuselah/.meteor/packages/fourseven_scss/.2.0.0-beta_1.zuywo8++os.osx.x86_64+web.browser+web.cordova/plugin.fourseven:scss.os.osx.x86_64/npm/fourseven:scss/node_modules/node-sass/vendor/darwin-x64/binding.node
Reason: image not found
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous>
(/Users/methuselah/.meteor/packages/fourseven_scss/.2.0.0-beta_1.zuywo8++os.osx.x86_64+web.browser+web.cordova/plugin.fourseven:scss.os.osx.x86_64/npm/fourseven:scss/node_modules/node-sass/lib/index.js:211:15)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object._.extend.Npm.require
(/Users/methuselah/.meteor/packages/meteor-tool/.1.0.38.1ohq3wg++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1327:22)
at Package (packages/fourseven:scss/plugin/compile-scss.js:2:1)
at <runJavaScript-53>:119:4
at <runJavaScript-53>:126:3
```

**Comment by fourseven** [comment]
Added an issue with meteor here - meteor/meteor#3483 . I'll give you a mention when I get a response, the build support isn't well documented.

**Comment by fourseven** [comment]
Also mentioning @wuworkshop here, who opened #56 (please continue the discussion in this thread).

**Comment by mattlinares** [comment]
Thanks.

**Comment by fourseven** [comment]
Alright I have an official update - 10.7 upwards is supported - https://github.com/meteor/meteor/issues/3483#issuecomment-70765759
